# Generated by Django 4.2.4 on 2024-01-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
