# Generated by Django 4.2.4 on 2024-01-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bridge', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='home_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
