# Generated by Django 4.2.20 on 2025-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bridge", "0012_alter_course_teacher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="module",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
