# Generated by Django 4.2.20 on 2025-04-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bridge", "0013_alter_course_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="class_picture",
            field=models.ImageField(blank=True, null=True, upload_to="class_pictures/"),
        ),
    ]
