# Generated by Django 4.2.4 on 2024-01-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bridge', '0004_module_course'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
