# Generated by Django 4.2.4 on 2024-01-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bridge', '0009_alter_course_modules_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_picture',
            field=models.URLField(blank=True, max_length=200000, null=True),
        ),
    ]
